### ISSUE TITLE
Resolve TODO comments

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#611]
This issue lists all the TODO comments throughout the codebase.  Each item needs to be investigated and marked resolved or moved to a new GitHub issue

- [ ] server/webhook_worker.go
[47](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/webhook_worker.go#L47):			// TODO save the payload here

- [ ] server/user_cloud.go 
[146](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/user_cloud.go#L146):		// TODO For https://github.com/mattermost/mattermost-plugin-jira/issues/149, need a channel ID

- [ ] server/http.go
[253](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/http.go#L253):				//TODO <><> prefix route with instance? or unnecessary since it's for all instances?

- [ ] server/utils/kvstore/cache.go
[85](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/utils/kvstore/cache.go#L85):		return errors.New("TODO: expiry not implemented yet")

- [ ] server/issue_parser.go
[116](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/issue_parser.go#L116):			// TODO is this supposed to be themed?

- [ ] server/stats.go
[144](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/stats.go#L144) :// TODO: Need a way to reset all stats in production?

- [ ] server/plugin.go
[179](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/plugin.go#L179):	// TODO: consider moving (some? stores? all?) initialization into the first OnConfig instead of OnActivate.

- [ ] webapp/src/actions/index.ts
[365](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/webapp/src/actions/index.ts#L365):        // TODO <> connectedInstances is still 2 after uninstalling an instance

- [ ] webapp/src/utils/posts.jsx
[4](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/webapp/src/utils/posts.jsx#L4):// TODO: change to use the isCombinedUserActivityPost in 'mattermost-redux/utils/post_list' when we upgrade to 5.12

- [ ] server/webhook.go
[70](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/webhook.go#L70):				// TODO is this supposed to be themed?

- [ ] server/user.go
[82](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/user.go#L82):	// TODO <> this block needs to be updated. Though idk if this route will still get called?
[141](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/user.go#L141):// TODO succinctly document the difference between start and connect

- [ ] server/command.go
[198](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/command.go#L198):	// TODO: Implement dynamic autocomplete for Jira issue (search)
[248](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/command.go#L248):	// TODO: Implement dynamic transition autocomplete
[258](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/command.go#L258):	// TODO: Implement dynamic Jira user search autocomplete
[457](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/command.go#L457):		// TODO: try to retrieve the issue anonymously
[717](https://github.com/mattermost/mattermost-plugin-ee-jira/blob/master/server/command.go#L717):// TODO should transition command post to channel? Options?

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
